### ISSUE TITLE
Doesn't reset on clear

### ISSUE THREAD

**Issue by kykydz** [FlatFilers/csvjson-app#111]
#### Instructions for filing an issue.

1. Save your testcase (click on the Save link in CSVJSON menu bar) and copy/paste the URL here.
- https://csvjson.com/json2csv/47be86143752fc1104b022902108d0fa
2. Describe your request.
- Copy and paste the value in JSON textbox
- Click convert
- Modify the value in textbox
- Click convert => value not change
- Clear => Paste => Modify value => Click convert => not change
- Refresh page Paste => Click convert => not change
- Refresh page without cache Paste => Click convert => not change
3. Platform Specification:
- OS Windows 10 Home
- Browser Chrome

**Comment by ashleygmulligan2** [comment]
This should now be fixed if you'd like to try again! Thank you for letting us know!
