### ISSUE TITLE
how to convert json to csvjson?

### ISSUE THREAD

**Issue by astrenofficial** [FlatFilers/csvjson-app#124]
https://csvjson.com/csvjson2json

**Comment by ashleygmulligan2** [comment]
Hey there, CSVJSON is a CSV-like text format where each line is a JSON array without the surrounding brackets.
For data made of numbers and 'simple' strings, CSVJSON looks just like CSV. Parsing CSVJSON is done by processing one line at a time. Wrap a line with square brackets [] and use JSON.parse() to convert to a JSON array. Let us know if you have any other questions!
