### ISSUE TITLE
Update title on CSVJSON > JSON page

### ISSUE THREAD

**Issue by alnoorp** [FlatFilers/csvjson-app#128]
Update title on CSVJSON > JSON page (right now says CSVJSON > CSV)
https://csvjson.com/csvjson2json

![image](https://user-images.githubusercontent.com/4617140/153533668-f3c38bf2-6e55-4cea-943f-111e3c1a66b3.png)

**Comment by ashleygmulligan2** [comment]
This is now fixed, thank you Alnoor.
