### ISSUE TITLE
JSON to CSV is broken on the website

### ISSUE THREAD

**Issue by cmmartin** [FlatFilers/csvjson-app#130]
https://csvjson.com/json2csv

Entire page is broken...

```
Uncaught TypeError: $issue.popover is not a function
```

Can't upload or even "clear" sample data

EDIT: Everything is broken not just JSON to CSV

**Comment by leighghunt** [comment]
Same here - seems to be limited to the file upload functionality - typing the CSV directly into the **Or paste your CSV here** text box still seems to work.

**Comment by ashleygmulligan2** [comment]
This should be fixed now. Thank you for reporting. Let us know if you see any other issues :)
