### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by Iliya5digital** [FlatFilers/csvjson-app#145]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1711571775600479)

#### Instructions for filing an issue.

1. [Save your testcase (click on the Save link in CSVJSON menu bar) and copy/paste the URL here.](http://jmeter.rf.gd/)
2. After uploading and changing a file aws_s3.php, shows 500 error

**Comment by Arsik36** [comment]
Hey there, thanks for reaching out! The link you shared is not valid for me. Is that the file you were trying to convert?<br><br>I am seeing that the Save button returns a 500 error. Is that the error you are referring to here?

**Comment by Iliya5digital** [comment]
yes

**Comment by Iliya5digital** [comment]
I made by our instructions, but not helpful

**Comment by Arsik36** [comment]
Thank you for confirming! We're looking into this, and will follow up once that error is resovled!

**Comment by sarocu** [comment]
@alnoorp is this the issue with CSVJSON where we upgraded the database?

**Comment by alnoorp** [comment]
@sarocu yes this is the one.

**Comment by sarocu** [comment]
can we close in that case?

**Comment by alnoorp** [comment]
@sarocu upgrading the database didn't resolve the issue for me.

**Comment by wmwassmann-gh** [comment]
Hey there, thanks for reaching out! The link you shared is not valid for me. Is that the file you were trying to convert? <br><br>I am seeing that the 'Save' button returns a 500 error. Is that the error you are referring to here?
